// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8j34gBLBPYzqwgTzV2cUB7NoDMZuWYOY',
    appId: '1:393671893802:web:34aaf3efd5b62d6f1a3453',
    messagingSenderId: '393671893802',
    projectId: 'dollawiz-4efda',
    authDomain: 'dollawiz-4efda.firebaseapp.com',
    storageBucket: 'dollawiz-4efda.firebasestorage.app',
    measurementId: 'G-VG0SDJ894C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfpuMsw1w6C8PHWXA1GL3WQZx6FZEg2Qg',
    appId: '1:393671893802:android:5f7e9daa8c605f5b1a3453',
    messagingSenderId: '393671893802',
    projectId: 'dollawiz-4efda',
    storageBucket: 'dollawiz-4efda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASeSB9JZb6BZSw9rbTtyH86LirA2u712I',
    appId: '1:393671893802:ios:61499e808635c7b61a3453',
    messagingSenderId: '393671893802',
    projectId: 'dollawiz-4efda',
    storageBucket: 'dollawiz-4efda.firebasestorage.app',
    iosBundleId: 'com.example.myFinanceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASeSB9JZb6BZSw9rbTtyH86LirA2u712I',
    appId: '1:393671893802:ios:61499e808635c7b61a3453',
    messagingSenderId: '393671893802',
    projectId: 'dollawiz-4efda',
    storageBucket: 'dollawiz-4efda.firebasestorage.app',
    iosBundleId: 'com.example.myFinanceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8j34gBLBPYzqwgTzV2cUB7NoDMZuWYOY',
    appId: '1:393671893802:web:6c75bd6ef004730d1a3453',
    messagingSenderId: '393671893802',
    projectId: 'dollawiz-4efda',
    authDomain: 'dollawiz-4efda.firebaseapp.com',
    storageBucket: 'dollawiz-4efda.firebasestorage.app',
    measurementId: 'G-J4YK92227G',
  );
}
